function gs_model_biquad_wfa_setup(hFPGA)
%--------------------------------------------------------------------------
% Software Interface Script Setup
% 
% Generated with MATLAB 9.9 (R2020b) at 00:00:56 on 21/03/2021.
% This function was created for the IP Core generated from design 'model_biquad_wfa'.
% 
% Run this function on an "fpga" object to configure it with the same interfaces as the generated IP core.
%--------------------------------------------------------------------------

%% AXI4-Lite
addAXI4SlaveInterface(hFPGA, ...
	"InterfaceID", "AXI4-Lite", ...
	"BaseAddress", 0x40010000, ...
	"AddressRange", 0x10000);

hPort_axi4_wkn = hdlcoder.DUTPort("axi4_wkn", ...
	"Direction", "IN", ...
	"DataType", numerictype(1,32,16), ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x104");

hPort_axi4_incos = hdlcoder.DUTPort("axi4_incos", ...
	"Direction", "IN", ...
	"DataType", numerictype(1,32,16), ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x100");

mapPort(hFPGA, [hPort_axi4_wkn, hPort_axi4_incos]);

%% AXI4-Stream
addAXI4StreamInterface(hFPGA, ...
	"InterfaceID", "AXI4-Stream", ...
	"WriteEnable", true, ...
	"WriteFrameLength", 1024, ...
	"ReadEnable", true, ...
	"ReadFrameLength", 1024);

hPort_axis_input_tdata = hdlcoder.DUTPort("axis_input_tdata", ...
	"Direction", "IN", ...
	"DataType", numerictype(1,32,16), ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Stream");

hPort_axis_output_tdata = hdlcoder.DUTPort("axis_output_tdata", ...
	"Direction", "OUT", ...
	"DataType", numerictype(1,32,16), ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Stream");

mapPort(hFPGA, [hPort_axis_input_tdata, hPort_axis_output_tdata]);

end
