-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/model_biquad_wfa/axis_goertzel_ip_src_goertzel_ip.vhd
-- Created: 2021-03-26 18:29:33
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: axis_goertzel_ip_src_goertzel_ip
-- Source Path: model_biquad_wfa/goertzel_ip
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY axis_goertzel_ip_src_goertzel_ip IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        input_tvalid                      :   IN    std_logic;
        input_tdata                       :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        wkn                               :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        incos                             :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        output_tdata                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        output_tvalid                     :   OUT   std_logic
        );
END axis_goertzel_ip_src_goertzel_ip;


ARCHITECTURE rtl OF axis_goertzel_ip_src_goertzel_ip IS

  -- Component Declarations
  COMPONENT axis_goertzel_ip_src_Subsystem
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          input_data                      :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          wkn                             :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          incos                           :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          Enable                          :   IN    std_logic;
          output_data                     :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En16
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : axis_goertzel_ip_src_Subsystem
    USE ENTITY work.axis_goertzel_ip_src_Subsystem(rtl);

  -- Signals
  SIGNAL Subsystem_out1                   : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  u_Subsystem : axis_goertzel_ip_src_Subsystem
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              input_data => input_tdata,  -- sfix32_En16
              wkn => wkn,  -- sfix32_En16
              incos => incos,  -- sfix32_En16
              Enable => input_tvalid,
              output_data => Subsystem_out1  -- sfix32_En16
              );

  output_tdata <= Subsystem_out1;

  output_tvalid <= input_tvalid;

END rtl;

