-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/model_biquad_wfa/axis_goertzel_ip_src_model_biquad_wfa.vhd
-- Created: 2021-03-26 18:29:33
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.001
-- Target subsystem base rate: 0.001
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        0.001
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- axis_output_tvalid            ce_out        0.001
-- axis_output_tdata             ce_out        0.001
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: axis_goertzel_ip_src_model_biquad_wfa
-- Source Path: model_biquad_wfa
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY axis_goertzel_ip_src_model_biquad_wfa IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        axis_input_tvalid                 :   IN    std_logic;
        axis_input_tdata                  :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        axi4_wkn                          :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        axi4_incos                        :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        ce_out                            :   OUT   std_logic;
        axis_output_tvalid                :   OUT   std_logic;
        axis_output_tdata                 :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En16
        );
END axis_goertzel_ip_src_model_biquad_wfa;


ARCHITECTURE rtl OF axis_goertzel_ip_src_model_biquad_wfa IS

  -- Component Declarations
  COMPONENT axis_goertzel_ip_src_goertzel_ip
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          input_tvalid                    :   IN    std_logic;
          input_tdata                     :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          wkn                             :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          incos                           :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          output_tdata                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          output_tvalid                   :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : axis_goertzel_ip_src_goertzel_ip
    USE ENTITY work.axis_goertzel_ip_src_goertzel_ip(rtl);

  -- Signals
  SIGNAL goertzel_ip_out1                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL goertzel_ip_out2                 : std_logic;

BEGIN
  u_goertzel_ip : axis_goertzel_ip_src_goertzel_ip
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              input_tvalid => axis_input_tvalid,
              input_tdata => axis_input_tdata,  -- sfix32_En16
              wkn => axi4_wkn,  -- sfix32_En16
              incos => axi4_incos,  -- sfix32_En16
              output_tdata => goertzel_ip_out1,  -- sfix32_En16
              output_tvalid => goertzel_ip_out2
              );

  ce_out <= clk_enable;

  axis_output_tvalid <= goertzel_ip_out2;

  axis_output_tdata <= goertzel_ip_out1;

END rtl;

