set_property SRC_FILE_INFO {cfile:/home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_axi_dma_mm2s_0/system_axi_dma_mm2s_0.xdc rfile:../../../vivado_prj.srcs/sources_1/bd/system/ip/system_axi_dma_mm2s_0/system_axi_dma_mm2s_0.xdc id:1 order:EARLY scoped_inst:system_i/axi_dma_mm2s/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_axi_dma_s2mm_0/system_axi_dma_s2mm_0.xdc rfile:../../../vivado_prj.srcs/sources_1/bd/system/ip/system_axi_dma_s2mm_0/system_axi_dma_s2mm_0.xdc id:2 order:EARLY scoped_inst:system_i/axi_dma_s2mm/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_sys_cpu_0/system_sys_cpu_0.xdc rfile:../../../vivado_prj.srcs/sources_1/bd/system/ip/system_sys_cpu_0/system_sys_cpu_0.xdc id:3 order:EARLY scoped_inst:system_i/sys_cpu/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../../../tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:4 order:LATE scoped_inst:system_i/axi_dma_mm2s_fifo/inst/gen_fifo.xpm_fifo_axis_inst/xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../../../tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:5 order:LATE scoped_inst:system_i/axi_dma_mm2s_fifo/inst/gen_fifo.xpm_fifo_axis_inst/xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../../../tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:6 order:LATE scoped_inst:system_i/axi_dma_s2mm_fifo/inst/gen_fifo.xpm_fifo_axis_inst/xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../../../tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:7 order:LATE scoped_inst:system_i/axi_dma_s2mm_fifo/inst/gen_fifo.xpm_fifo_axis_inst/xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../../../tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:8 order:LATE scoped_inst:system_i/axi_dma_mm2s_fifo/inst/gen_fifo.xpm_fifo_axis_inst/xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../../../tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:9 order:LATE scoped_inst:system_i/axi_dma_s2mm_fifo/inst/gen_fifo.xpm_fifo_axis_inst/xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../../../tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:10 order:LATE scoped_inst:system_i/axi_dma_mm2s_fifo/inst/gen_fifo.xpm_fifo_axis_inst/xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../../../tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:11 order:LATE scoped_inst:system_i/axi_dma_s2mm_fifo/inst/gen_fifo.xpm_fifo_axis_inst/xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_handshake.tcl rfile:../../../../../../../../../../../tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_handshake.tcl id:12 order:LATE scoped_inst:system_i/axi_cpu_interconnect/m00_couplers/auto_cc/inst/gen_clock_conv.gen_async_lite_conv.clock_conv_lite_fwd_ar/handshake unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_handshake.tcl rfile:../../../../../../../../../../../tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_handshake.tcl id:13 order:LATE scoped_inst:system_i/axi_cpu_interconnect/m00_couplers/auto_cc/inst/gen_clock_conv.gen_async_lite_conv.clock_conv_lite_fwd_aw/handshake unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_handshake.tcl rfile:../../../../../../../../../../../tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_handshake.tcl id:14 order:LATE scoped_inst:system_i/axi_cpu_interconnect/m00_couplers/auto_cc/inst/gen_clock_conv.gen_async_lite_conv.clock_conv_lite_fwd_w/handshake unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_handshake.tcl rfile:../../../../../../../../../../../tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_handshake.tcl id:15 order:LATE scoped_inst:system_i/axi_cpu_interconnect/m00_couplers/auto_cc/inst/gen_clock_conv.gen_async_lite_conv.clock_conv_lite_resp_b/handshake unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_handshake.tcl rfile:../../../../../../../../../../../tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_handshake.tcl id:16 order:LATE scoped_inst:system_i/axi_cpu_interconnect/m00_couplers/auto_cc/inst/gen_clock_conv.gen_async_lite_conv.clock_conv_lite_resp_r/handshake unmanaged:yes} [current_design]
current_instance system_i/axi_dma_mm2s/U0
set_property src_info {type:SCOPED_XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -type CDC -id {CDC-1} -user "axi_dma" -tags "9601" -desc "The CDC-1 warning is waived as it is safe in the context of AXI DMA. The Address and Data value does not change until AXI transaction is complete." -to [get_pins -hier -quiet -filter {NAME =~*I_AXI_DMA_REG_MODULE/GEN_AXI_LITE_IF.AXI_LITE_IF_I/GEN_ASYNC_WRITE.REG_WADDR_TO_IPCLK/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.FOR_IN_cdc_to[*].CROSS2_PLEVEL_IN2SCNDRY_IN_cdc_to/D}]
set_property src_info {type:SCOPED_XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -type CDC -id {CDC-1} -user "axi_dma" -tags "9601" -desc "The CDC-1 warning is waived as it is safe in the context of AXI DMA. The Address and Data value does not change until AXI transaction is complete." -to [get_pins -hier -quiet -filter {NAME =~*I_AXI_DMA_REG_MODULE/GEN_AXI_LITE_IF.AXI_LITE_IF_I/GEN_ASYNC_WRITE.REG_WADDR_TO_IPCLK1/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.FOR_IN_cdc_to[*].CROSS2_PLEVEL_IN2SCNDRY_IN_cdc_to/D}]
set_property src_info {type:SCOPED_XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -type CDC -id {CDC-1} -user "axi_dma" -tags "9601" -desc "The CDC-1 warning is waived as it is safe in the context of AXI DMA. In multi channel mode, it is safe to ignore this." -from [get_pins -hier -quiet -filter {NAME =~*MM2S_SPLIT.I_COMMAND_MM2S_SPLITTER/vsize_data_int_reg[*]/C}]
current_instance
current_instance system_i/axi_dma_s2mm/U0
set_property src_info {type:SCOPED_XDC file:2 line:52 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -type CDC -id {CDC-1} -user "axi_dma" -tags "9601" -desc "The CDC-1 warning is waived as it is safe in the context of AXI DMA. The Address and Data value does not change until AXI transaction is complete." -to [get_pins -hier -quiet -filter {NAME =~*I_AXI_DMA_REG_MODULE/GEN_AXI_LITE_IF.AXI_LITE_IF_I/GEN_ASYNC_WRITE.REG_WADDR_TO_IPCLK/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.FOR_IN_cdc_to[*].CROSS2_PLEVEL_IN2SCNDRY_IN_cdc_to/D}]
set_property src_info {type:SCOPED_XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -type CDC -id {CDC-1} -user "axi_dma" -tags "9601" -desc "The CDC-1 warning is waived as it is safe in the context of AXI DMA. The Address and Data value does not change until AXI transaction is complete." -to [get_pins -hier -quiet -filter {NAME =~*I_AXI_DMA_REG_MODULE/GEN_AXI_LITE_IF.AXI_LITE_IF_I/GEN_ASYNC_WRITE.REG_WADDR_TO_IPCLK1/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.FOR_IN_cdc_to[*].CROSS2_PLEVEL_IN2SCNDRY_IN_cdc_to/D}]
set_property src_info {type:SCOPED_XDC file:2 line:61 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -type CDC -id {CDC-1} -user "axi_dma" -tags "9601" -desc "The CDC-1 warning is waived as it is safe in the context of AXI DMA. In multi channel mode, it is safe to ignore this." -from [get_pins -hier -quiet -filter {NAME =~*MM2S_SPLIT.I_COMMAND_MM2S_SPLITTER/vsize_data_int_reg[*]/C}]
current_instance
current_instance system_i/sys_cpu/inst
set_property src_info {type:SCOPED_XDC file:3 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_fpga_0 0.3
set_property src_info {type:SCOPED_XDC file:3 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_fpga_1 0.15
set_property src_info {type:SCOPED_XDC file:3 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C11" [get_ports "MIO[53]"]
set_property src_info {type:SCOPED_XDC file:3 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D13" [get_ports "MIO[52]"]
set_property src_info {type:SCOPED_XDC file:3 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C13" [get_ports "MIO[51]"]
set_property src_info {type:SCOPED_XDC file:3 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D10" [get_ports "MIO[50]"]
set_property src_info {type:SCOPED_XDC file:3 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C9" [get_ports "MIO[49]"]
set_property src_info {type:SCOPED_XDC file:3 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D12" [get_ports "MIO[48]"]
set_property src_info {type:SCOPED_XDC file:3 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B13" [get_ports "MIO[47]"]
set_property src_info {type:SCOPED_XDC file:3 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D11" [get_ports "MIO[46]"]
set_property src_info {type:SCOPED_XDC file:3 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B14" [get_ports "MIO[45]"]
set_property src_info {type:SCOPED_XDC file:3 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E10" [get_ports "MIO[44]"]
set_property src_info {type:SCOPED_XDC file:3 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B12" [get_ports "MIO[43]"]
set_property src_info {type:SCOPED_XDC file:3 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D15" [get_ports "MIO[42]"]
set_property src_info {type:SCOPED_XDC file:3 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C15" [get_ports "MIO[41]"]
set_property src_info {type:SCOPED_XDC file:3 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E9" [get_ports "MIO[40]"]
set_property src_info {type:SCOPED_XDC file:3 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C10" [get_ports "MIO[39]"]
set_property src_info {type:SCOPED_XDC file:3 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F10" [get_ports "MIO[38]"]
set_property src_info {type:SCOPED_XDC file:3 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B9" [get_ports "MIO[37]"]
set_property src_info {type:SCOPED_XDC file:3 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A14" [get_ports "MIO[36]"]
set_property src_info {type:SCOPED_XDC file:3 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F9" [get_ports "MIO[35]"]
set_property src_info {type:SCOPED_XDC file:3 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B11" [get_ports "MIO[34]"]
set_property src_info {type:SCOPED_XDC file:3 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G11" [get_ports "MIO[33]"]
set_property src_info {type:SCOPED_XDC file:3 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C16" [get_ports "MIO[32]"]
set_property src_info {type:SCOPED_XDC file:3 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F14" [get_ports "MIO[31]"]
set_property src_info {type:SCOPED_XDC file:3 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A12" [get_ports "MIO[30]"]
set_property src_info {type:SCOPED_XDC file:3 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E15" [get_ports "MIO[29]"]
set_property src_info {type:SCOPED_XDC file:3 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A11" [get_ports "MIO[28]"]
set_property src_info {type:SCOPED_XDC file:3 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D16" [get_ports "MIO[27]"]
set_property src_info {type:SCOPED_XDC file:3 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A10" [get_ports "MIO[26]"]
set_property src_info {type:SCOPED_XDC file:3 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F11" [get_ports "MIO[25]"]
set_property src_info {type:SCOPED_XDC file:3 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B16" [get_ports "MIO[24]"]
set_property src_info {type:SCOPED_XDC file:3 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E12" [get_ports "MIO[23]"]
set_property src_info {type:SCOPED_XDC file:3 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A9" [get_ports "MIO[22]"]
set_property src_info {type:SCOPED_XDC file:3 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F12" [get_ports "MIO[21]"]
set_property src_info {type:SCOPED_XDC file:3 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A15" [get_ports "MIO[20]"]
set_property src_info {type:SCOPED_XDC file:3 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E13" [get_ports "MIO[19]"]
set_property src_info {type:SCOPED_XDC file:3 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A16" [get_ports "MIO[18]"]
set_property src_info {type:SCOPED_XDC file:3 line:250 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E14" [get_ports "MIO[17]"]
set_property src_info {type:SCOPED_XDC file:3 line:256 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D17" [get_ports "MIO[16]"]
set_property src_info {type:SCOPED_XDC file:3 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E17" [get_ports "MIO[15]"]
set_property src_info {type:SCOPED_XDC file:3 line:268 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B17" [get_ports "MIO[14]"]
set_property src_info {type:SCOPED_XDC file:3 line:274 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A17" [get_ports "MIO[13]"]
set_property src_info {type:SCOPED_XDC file:3 line:280 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C18" [get_ports "MIO[12]"]
set_property src_info {type:SCOPED_XDC file:3 line:286 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B19" [get_ports "MIO[11]"]
set_property src_info {type:SCOPED_XDC file:3 line:292 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G16" [get_ports "MIO[10]"]
set_property src_info {type:SCOPED_XDC file:3 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C19" [get_ports "MIO[9]"]
set_property src_info {type:SCOPED_XDC file:3 line:304 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E18" [get_ports "MIO[8]"]
set_property src_info {type:SCOPED_XDC file:3 line:310 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D18" [get_ports "MIO[7]"]
set_property src_info {type:SCOPED_XDC file:3 line:316 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A19" [get_ports "MIO[6]"]
set_property src_info {type:SCOPED_XDC file:3 line:322 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A20" [get_ports "MIO[5]"]
set_property src_info {type:SCOPED_XDC file:3 line:328 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E19" [get_ports "MIO[4]"]
set_property src_info {type:SCOPED_XDC file:3 line:334 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F17" [get_ports "MIO[3]"]
set_property src_info {type:SCOPED_XDC file:3 line:340 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A21" [get_ports "MIO[2]"]
set_property src_info {type:SCOPED_XDC file:3 line:346 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A22" [get_ports "MIO[1]"]
set_property src_info {type:SCOPED_XDC file:3 line:352 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G17" [get_ports "MIO[0]"]
set_property src_info {type:SCOPED_XDC file:3 line:357 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N16" [get_ports "DDR_VRP"]
set_property src_info {type:SCOPED_XDC file:3 line:361 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M16" [get_ports "DDR_VRN"]
set_property src_info {type:SCOPED_XDC file:3 line:365 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R19" [get_ports "DDR_WEB"]
set_property src_info {type:SCOPED_XDC file:3 line:369 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R18" [get_ports "DDR_RAS_n"]
set_property src_info {type:SCOPED_XDC file:3 line:373 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P18" [get_ports "DDR_ODT"]
set_property src_info {type:SCOPED_XDC file:3 line:377 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F20" [get_ports "DDR_DRSTB"]
set_property src_info {type:SCOPED_XDC file:3 line:381 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "V21" [get_ports "DDR_DQS[3]"]
set_property src_info {type:SCOPED_XDC file:3 line:385 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N21" [get_ports "DDR_DQS[2]"]
set_property src_info {type:SCOPED_XDC file:3 line:389 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H21" [get_ports "DDR_DQS[1]"]
set_property src_info {type:SCOPED_XDC file:3 line:393 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C21" [get_ports "DDR_DQS[0]"]
set_property src_info {type:SCOPED_XDC file:3 line:397 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "W21" [get_ports "DDR_DQS_n[3]"]
set_property src_info {type:SCOPED_XDC file:3 line:401 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P21" [get_ports "DDR_DQS_n[2]"]
set_property src_info {type:SCOPED_XDC file:3 line:405 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J21" [get_ports "DDR_DQS_n[1]"]
set_property src_info {type:SCOPED_XDC file:3 line:409 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D21" [get_ports "DDR_DQS_n[0]"]
set_property src_info {type:SCOPED_XDC file:3 line:413 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G22" [get_ports "DDR_DQ[9]"]
set_property src_info {type:SCOPED_XDC file:3 line:417 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G21" [get_ports "DDR_DQ[8]"]
set_property src_info {type:SCOPED_XDC file:3 line:421 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F22" [get_ports "DDR_DQ[7]"]
set_property src_info {type:SCOPED_XDC file:3 line:425 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F21" [get_ports "DDR_DQ[6]"]
set_property src_info {type:SCOPED_XDC file:3 line:429 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E22" [get_ports "DDR_DQ[5]"]
set_property src_info {type:SCOPED_XDC file:3 line:433 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E20" [get_ports "DDR_DQ[4]"]
set_property src_info {type:SCOPED_XDC file:3 line:437 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D20" [get_ports "DDR_DQ[3]"]
set_property src_info {type:SCOPED_XDC file:3 line:441 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "Y22" [get_ports "DDR_DQ[31]"]
set_property src_info {type:SCOPED_XDC file:3 line:445 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "V20" [get_ports "DDR_DQ[30]"]
set_property src_info {type:SCOPED_XDC file:3 line:449 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B21" [get_ports "DDR_DQ[2]"]
set_property src_info {type:SCOPED_XDC file:3 line:453 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "W20" [get_ports "DDR_DQ[29]"]
set_property src_info {type:SCOPED_XDC file:3 line:457 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "W22" [get_ports "DDR_DQ[28]"]
set_property src_info {type:SCOPED_XDC file:3 line:461 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "U21" [get_ports "DDR_DQ[27]"]
set_property src_info {type:SCOPED_XDC file:3 line:465 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "AA22" [get_ports "DDR_DQ[26]"]
set_property src_info {type:SCOPED_XDC file:3 line:469 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "U22" [get_ports "DDR_DQ[25]"]
set_property src_info {type:SCOPED_XDC file:3 line:473 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "Y20" [get_ports "DDR_DQ[24]"]
set_property src_info {type:SCOPED_XDC file:3 line:477 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R22" [get_ports "DDR_DQ[23]"]
set_property src_info {type:SCOPED_XDC file:3 line:481 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M21" [get_ports "DDR_DQ[22]"]
set_property src_info {type:SCOPED_XDC file:3 line:485 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "T21" [get_ports "DDR_DQ[21]"]
set_property src_info {type:SCOPED_XDC file:3 line:489 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "R20" [get_ports "DDR_DQ[20]"]
set_property src_info {type:SCOPED_XDC file:3 line:493 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C20" [get_ports "DDR_DQ[1]"]
set_property src_info {type:SCOPED_XDC file:3 line:497 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "T22" [get_ports "DDR_DQ[19]"]
set_property src_info {type:SCOPED_XDC file:3 line:501 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N20" [get_ports "DDR_DQ[18]"]
set_property src_info {type:SCOPED_XDC file:3 line:505 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "T20" [get_ports "DDR_DQ[17]"]
set_property src_info {type:SCOPED_XDC file:3 line:509 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M22" [get_ports "DDR_DQ[16]"]
set_property src_info {type:SCOPED_XDC file:3 line:513 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K20" [get_ports "DDR_DQ[15]"]
set_property src_info {type:SCOPED_XDC file:3 line:517 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J22" [get_ports "DDR_DQ[14]"]
set_property src_info {type:SCOPED_XDC file:3 line:521 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K22" [get_ports "DDR_DQ[13]"]
set_property src_info {type:SCOPED_XDC file:3 line:525 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L20" [get_ports "DDR_DQ[12]"]
set_property src_info {type:SCOPED_XDC file:3 line:529 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L21" [get_ports "DDR_DQ[11]"]
set_property src_info {type:SCOPED_XDC file:3 line:533 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L22" [get_ports "DDR_DQ[10]"]
set_property src_info {type:SCOPED_XDC file:3 line:537 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D22" [get_ports "DDR_DQ[0]"]
set_property src_info {type:SCOPED_XDC file:3 line:541 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "AA21" [get_ports "DDR_DM[3]"]
set_property src_info {type:SCOPED_XDC file:3 line:545 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P22" [get_ports "DDR_DM[2]"]
set_property src_info {type:SCOPED_XDC file:3 line:549 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H20" [get_ports "DDR_DM[1]"]
set_property src_info {type:SCOPED_XDC file:3 line:553 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B22" [get_ports "DDR_DM[0]"]
set_property src_info {type:SCOPED_XDC file:3 line:557 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P17" [get_ports "DDR_CS_n"]
set_property src_info {type:SCOPED_XDC file:3 line:561 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "T19" [get_ports "DDR_CKE"]
set_property src_info {type:SCOPED_XDC file:3 line:565 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N19" [get_ports "DDR_Clk"]
set_property src_info {type:SCOPED_XDC file:3 line:569 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N18" [get_ports "DDR_Clk_n"]
set_property src_info {type:SCOPED_XDC file:3 line:573 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "P20" [get_ports "DDR_CAS_n"]
set_property src_info {type:SCOPED_XDC file:3 line:577 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M17" [get_ports "DDR_BankAddr[2]"]
set_property src_info {type:SCOPED_XDC file:3 line:581 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L17" [get_ports "DDR_BankAddr[1]"]
set_property src_info {type:SCOPED_XDC file:3 line:585 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L16" [get_ports "DDR_BankAddr[0]"]
set_property src_info {type:SCOPED_XDC file:3 line:589 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H18" [get_ports "DDR_Addr[9]"]
set_property src_info {type:SCOPED_XDC file:3 line:593 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J18" [get_ports "DDR_Addr[8]"]
set_property src_info {type:SCOPED_XDC file:3 line:597 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J17" [get_ports "DDR_Addr[7]"]
set_property src_info {type:SCOPED_XDC file:3 line:601 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J16" [get_ports "DDR_Addr[6]"]
set_property src_info {type:SCOPED_XDC file:3 line:605 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K18" [get_ports "DDR_Addr[5]"]
set_property src_info {type:SCOPED_XDC file:3 line:609 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K17" [get_ports "DDR_Addr[4]"]
set_property src_info {type:SCOPED_XDC file:3 line:613 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L19" [get_ports "DDR_Addr[3]"]
set_property src_info {type:SCOPED_XDC file:3 line:617 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K19" [get_ports "DDR_Addr[2]"]
set_property src_info {type:SCOPED_XDC file:3 line:621 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M18" [get_ports "DDR_Addr[1]"]
set_property src_info {type:SCOPED_XDC file:3 line:625 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G19" [get_ports "DDR_Addr[14]"]
set_property src_info {type:SCOPED_XDC file:3 line:629 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F19" [get_ports "DDR_Addr[13]"]
set_property src_info {type:SCOPED_XDC file:3 line:633 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H19" [get_ports "DDR_Addr[12]"]
set_property src_info {type:SCOPED_XDC file:3 line:637 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G18" [get_ports "DDR_Addr[11]"]
set_property src_info {type:SCOPED_XDC file:3 line:641 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J20" [get_ports "DDR_Addr[10]"]
set_property src_info {type:SCOPED_XDC file:3 line:645 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M19" [get_ports "DDR_Addr[0]"]
set_property src_info {type:SCOPED_XDC file:3 line:649 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B18" [get_ports "PS_PORB"]
set_property src_info {type:SCOPED_XDC file:3 line:652 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C14" [get_ports "PS_SRSTB"]
set_property src_info {type:SCOPED_XDC file:3 line:655 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F16" [get_ports "PS_CLK"]
current_instance
current_instance system_i/axi_dma_mm2s_fifo/inst/gen_fifo.xpm_fifo_axis_inst/xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:4 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance system_i/axi_dma_mm2s_fifo/inst/gen_fifo.xpm_fifo_axis_inst/xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:5 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance system_i/axi_dma_s2mm_fifo/inst/gen_fifo.xpm_fifo_axis_inst/xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:6 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance system_i/axi_dma_s2mm_fifo/inst/gen_fifo.xpm_fifo_axis_inst/xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:7 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance system_i/axi_dma_mm2s_fifo/inst/gen_fifo.xpm_fifo_axis_inst/xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst
set_property src_info {type:SCOPED_XDC file:8 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance system_i/axi_dma_s2mm_fifo/inst/gen_fifo.xpm_fifo_axis_inst/xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst
set_property src_info {type:SCOPED_XDC file:9 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance system_i/axi_dma_mm2s_fifo/inst/gen_fifo.xpm_fifo_axis_inst/xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst
set_property src_info {type:SCOPED_XDC file:10 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance system_i/axi_dma_s2mm_fifo/inst/gen_fifo.xpm_fifo_axis_inst/xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst
set_property src_info {type:SCOPED_XDC file:11 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance system_i/axi_cpu_interconnect/m00_couplers/auto_cc/inst/gen_clock_conv.gen_async_lite_conv.clock_conv_lite_fwd_ar/handshake
set_property src_info {type:SCOPED_XDC file:12 line:30 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-15} -user "xpm_cdc" -tags "1009444" -desc "The CDC-15 warning is waived as it is safe in the context of XPM_CDC_HANDSHAKE." -from [get_pins -quiet {src_hsdata_ff_reg*/C}] -to [get_pins -quiet {dest_hsdata_ff_reg*/D}]
current_instance
current_instance system_i/axi_cpu_interconnect/m00_couplers/auto_cc/inst/gen_clock_conv.gen_async_lite_conv.clock_conv_lite_fwd_aw/handshake
set_property src_info {type:SCOPED_XDC file:13 line:30 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-15} -user "xpm_cdc" -tags "1009444" -desc "The CDC-15 warning is waived as it is safe in the context of XPM_CDC_HANDSHAKE." -from [get_pins -quiet {src_hsdata_ff_reg*/C}] -to [get_pins -quiet {dest_hsdata_ff_reg*/D}]
current_instance
current_instance system_i/axi_cpu_interconnect/m00_couplers/auto_cc/inst/gen_clock_conv.gen_async_lite_conv.clock_conv_lite_fwd_w/handshake
set_property src_info {type:SCOPED_XDC file:14 line:30 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-15} -user "xpm_cdc" -tags "1009444" -desc "The CDC-15 warning is waived as it is safe in the context of XPM_CDC_HANDSHAKE." -from [get_pins -quiet {src_hsdata_ff_reg*/C}] -to [get_pins -quiet {dest_hsdata_ff_reg*/D}]
current_instance
current_instance system_i/axi_cpu_interconnect/m00_couplers/auto_cc/inst/gen_clock_conv.gen_async_lite_conv.clock_conv_lite_resp_b/handshake
set_property src_info {type:SCOPED_XDC file:15 line:30 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-15} -user "xpm_cdc" -tags "1009444" -desc "The CDC-15 warning is waived as it is safe in the context of XPM_CDC_HANDSHAKE." -from [get_pins -quiet {src_hsdata_ff_reg*/C}] -to [get_pins -quiet {dest_hsdata_ff_reg*/D}]
current_instance
current_instance system_i/axi_cpu_interconnect/m00_couplers/auto_cc/inst/gen_clock_conv.gen_async_lite_conv.clock_conv_lite_resp_r/handshake
set_property src_info {type:SCOPED_XDC file:16 line:30 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-15} -user "xpm_cdc" -tags "1009444" -desc "The CDC-15 warning is waived as it is safe in the context of XPM_CDC_HANDSHAKE." -from [get_pins -quiet {src_hsdata_ff_reg*/C}] -to [get_pins -quiet {dest_hsdata_ff_reg*/D}]
