# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_axi_clkwiz_0/system_axi_clkwiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_clkwiz_0 || ORIG_REF_NAME==system_axi_clkwiz_0} -quiet] -quiet

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_cpu_interconnect_0/system_axi_cpu_interconnect_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_cpu_interconnect_0 || ORIG_REF_NAME==system_axi_cpu_interconnect_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_dma_mm2s_0/system_axi_dma_mm2s_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_dma_mm2s_0 || ORIG_REF_NAME==system_axi_dma_mm2s_0} -quiet] -quiet

# IP: bd/system/ip/system_xbar_1/system_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_1 || ORIG_REF_NAME==system_xbar_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_dma_mm2s_cpu_ic_0/system_axi_dma_mm2s_cpu_ic_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_dma_mm2s_cpu_ic_0 || ORIG_REF_NAME==system_axi_dma_mm2s_cpu_ic_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_dma_mm2s_fifo_0/system_axi_dma_mm2s_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_dma_mm2s_fifo_0 || ORIG_REF_NAME==system_axi_dma_mm2s_fifo_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_dma_s2mm_0/system_axi_dma_s2mm_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_dma_s2mm_0 || ORIG_REF_NAME==system_axi_dma_s2mm_0} -quiet] -quiet

# IP: bd/system/ip/system_xbar_2/system_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_2 || ORIG_REF_NAME==system_xbar_2} -quiet] -quiet

# IP: bd/system/ip/system_axi_dma_s2mm_cpu_ic_0/system_axi_dma_s2mm_cpu_ic_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_dma_s2mm_cpu_ic_0 || ORIG_REF_NAME==system_axi_dma_s2mm_cpu_ic_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_dma_s2mm_fifo_0/system_axi_dma_s2mm_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_dma_s2mm_fifo_0 || ORIG_REF_NAME==system_axi_dma_s2mm_fifo_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gp_rstgen_0/system_axi_gp_rstgen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gp_rstgen_0 || ORIG_REF_NAME==system_axi_gp_rstgen_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_hp_rstgen_0/system_axi_hp_rstgen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_hp_rstgen_0 || ORIG_REF_NAME==system_axi_hp_rstgen_0} -quiet] -quiet

# IP: bd/system/ip/system_const_intr_concat_gnd_0/system_const_intr_concat_gnd_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_const_intr_concat_gnd_0 || ORIG_REF_NAME==system_const_intr_concat_gnd_0} -quiet] -quiet

# IP: bd/system/ip/system_core_clkwiz_0/system_core_clkwiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_core_clkwiz_0 || ORIG_REF_NAME==system_core_clkwiz_0} -quiet] -quiet

# IP: bd/system/ip/system_intr_concat_0/system_intr_concat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_intr_concat_0 || ORIG_REF_NAME==system_intr_concat_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_core_rstgen_0/system_sys_core_rstgen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_core_rstgen_0 || ORIG_REF_NAME==system_sys_core_rstgen_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_cpu_0/system_sys_cpu_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sys_cpu_0 || ORIG_REF_NAME==system_sys_cpu_0} -quiet] -quiet

# IP: bd/system/ip/system_axis_goertzel_ip_0_0/system_axis_goertzel_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_goertzel_ip_0_0 || ORIG_REF_NAME==system_axis_goertzel_ip_0_0} -quiet] -quiet

# IP: bd/system/ip/system_s00_regslice_6/system_s00_regslice_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_s00_regslice_6 || ORIG_REF_NAME==system_s00_regslice_6} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_cc_0/system_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_0 || ORIG_REF_NAME==system_auto_cc_0} -quiet] -quiet

# IP: bd/system/ip/system_m01_regslice_0/system_m01_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m01_regslice_0 || ORIG_REF_NAME==system_m01_regslice_0} -quiet] -quiet

# IP: bd/system/ip/system_m02_regslice_0/system_m02_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m02_regslice_0 || ORIG_REF_NAME==system_m02_regslice_0} -quiet] -quiet

# IP: bd/system/ip/system_s00_regslice_7/system_s00_regslice_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_s00_regslice_7 || ORIG_REF_NAME==system_s00_regslice_7} -quiet] -quiet

# IP: bd/system/ip/system_auto_us_0/system_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_0 || ORIG_REF_NAME==system_auto_us_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_rs_w_0/system_auto_rs_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_rs_w_0 || ORIG_REF_NAME==system_auto_rs_w_0} -quiet] -quiet

# IP: bd/system/ip/system_s01_regslice_4/system_s01_regslice_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_s01_regslice_4 || ORIG_REF_NAME==system_s01_regslice_4} -quiet] -quiet

# IP: bd/system/ip/system_m00_regslice_4/system_m00_regslice_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m00_regslice_4 || ORIG_REF_NAME==system_m00_regslice_4} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_1/system_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_1 || ORIG_REF_NAME==system_auto_pc_1} -quiet] -quiet

# IP: bd/system/ip/system_s00_regslice_8/system_s00_regslice_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_s00_regslice_8 || ORIG_REF_NAME==system_s00_regslice_8} -quiet] -quiet

# IP: bd/system/ip/system_auto_us_1/system_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_1 || ORIG_REF_NAME==system_auto_us_1} -quiet] -quiet

# IP: bd/system/ip/system_auto_rs_w_1/system_auto_rs_w_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_rs_w_1 || ORIG_REF_NAME==system_auto_rs_w_1} -quiet] -quiet

# IP: bd/system/ip/system_s01_regslice_5/system_s01_regslice_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_s01_regslice_5 || ORIG_REF_NAME==system_s01_regslice_5} -quiet] -quiet

# IP: bd/system/ip/system_m00_regslice_5/system_m00_regslice_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_m00_regslice_5 || ORIG_REF_NAME==system_m00_regslice_5} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_2/system_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_2 || ORIG_REF_NAME==system_auto_pc_2} -quiet] -quiet

# XDC: bd/system/ip/system_axi_clkwiz_0/system_axi_clkwiz_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_clkwiz_0 || ORIG_REF_NAME==system_axi_clkwiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_clkwiz_0/system_axi_clkwiz_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_clkwiz_0 || ORIG_REF_NAME==system_axi_clkwiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_clkwiz_0/system_axi_clkwiz_0_ooc.xdc

# XDC: bd/system/ip/system_axi_dma_mm2s_0/system_axi_dma_mm2s_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_dma_mm2s_0 || ORIG_REF_NAME==system_axi_dma_mm2s_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_dma_mm2s_0/system_axi_dma_mm2s_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_dma_mm2s_0 || ORIG_REF_NAME==system_axi_dma_mm2s_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_dma_s2mm_0/system_axi_dma_s2mm_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_dma_s2mm_0 || ORIG_REF_NAME==system_axi_dma_s2mm_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_dma_s2mm_0/system_axi_dma_s2mm_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_dma_s2mm_0 || ORIG_REF_NAME==system_axi_dma_s2mm_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_gp_rstgen_0/system_axi_gp_rstgen_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gp_rstgen_0 || ORIG_REF_NAME==system_axi_gp_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_gp_rstgen_0/system_axi_gp_rstgen_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gp_rstgen_0 || ORIG_REF_NAME==system_axi_gp_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_hp_rstgen_0/system_axi_hp_rstgen_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_hp_rstgen_0 || ORIG_REF_NAME==system_axi_hp_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_axi_hp_rstgen_0/system_axi_hp_rstgen_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_hp_rstgen_0 || ORIG_REF_NAME==system_axi_hp_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_core_clkwiz_0/system_core_clkwiz_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_core_clkwiz_0 || ORIG_REF_NAME==system_core_clkwiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_core_clkwiz_0/system_core_clkwiz_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_core_clkwiz_0 || ORIG_REF_NAME==system_core_clkwiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_core_clkwiz_0/system_core_clkwiz_0_ooc.xdc

# XDC: bd/system/ip/system_sys_core_rstgen_0/system_sys_core_rstgen_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_core_rstgen_0 || ORIG_REF_NAME==system_sys_core_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_sys_core_rstgen_0/system_sys_core_rstgen_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_core_rstgen_0 || ORIG_REF_NAME==system_sys_core_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/ip/system_sys_cpu_0/system_sys_cpu_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_cpu_0 || ORIG_REF_NAME==system_sys_cpu_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_s00_regslice_6/system_s00_regslice_6_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_s00_regslice_6 || ORIG_REF_NAME==system_s00_regslice_6} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_s00_regslice_6/system_s00_regslice_6_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc

# XDC: bd/system/ip/system_auto_cc_0/system_auto_cc_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_cc_0 || ORIG_REF_NAME==system_auto_cc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_auto_cc_0/system_auto_cc_0_ooc.xdc

# XDC: bd/system/ip/system_m01_regslice_0/system_m01_regslice_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_m01_regslice_0 || ORIG_REF_NAME==system_m01_regslice_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_m01_regslice_0/system_m01_regslice_0_ooc.xdc

# XDC: bd/system/ip/system_m02_regslice_0/system_m02_regslice_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_m02_regslice_0 || ORIG_REF_NAME==system_m02_regslice_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_m02_regslice_0/system_m02_regslice_0_ooc.xdc

# XDC: bd/system/ip/system_s00_regslice_7/system_s00_regslice_7_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_s00_regslice_7 || ORIG_REF_NAME==system_s00_regslice_7} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_s00_regslice_7/system_s00_regslice_7_ooc.xdc

# XDC: bd/system/ip/system_auto_us_0/system_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_us_0 || ORIG_REF_NAME==system_auto_us_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_auto_us_0/system_auto_us_0_ooc.xdc

# XDC: bd/system/ip/system_auto_rs_w_0/system_auto_rs_w_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_rs_w_0 || ORIG_REF_NAME==system_auto_rs_w_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_auto_rs_w_0/system_auto_rs_w_0_ooc.xdc

# XDC: bd/system/ip/system_s01_regslice_4/system_s01_regslice_4_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_s01_regslice_4 || ORIG_REF_NAME==system_s01_regslice_4} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_s01_regslice_4/system_s01_regslice_4_ooc.xdc

# XDC: bd/system/ip/system_m00_regslice_4/system_m00_regslice_4_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_m00_regslice_4 || ORIG_REF_NAME==system_m00_regslice_4} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_m00_regslice_4/system_m00_regslice_4_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc

# XDC: bd/system/ip/system_s00_regslice_8/system_s00_regslice_8_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_s00_regslice_8 || ORIG_REF_NAME==system_s00_regslice_8} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_s00_regslice_8/system_s00_regslice_8_ooc.xdc

# XDC: bd/system/ip/system_auto_us_1/system_auto_us_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_us_1 || ORIG_REF_NAME==system_auto_us_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_auto_us_1/system_auto_us_1_ooc.xdc

# XDC: bd/system/ip/system_auto_rs_w_1/system_auto_rs_w_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_rs_w_1 || ORIG_REF_NAME==system_auto_rs_w_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_auto_rs_w_1/system_auto_rs_w_1_ooc.xdc

# XDC: bd/system/ip/system_s01_regslice_5/system_s01_regslice_5_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_s01_regslice_5 || ORIG_REF_NAME==system_s01_regslice_5} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_s01_regslice_5/system_s01_regslice_5_ooc.xdc

# XDC: bd/system/ip/system_m00_regslice_5/system_m00_regslice_5_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_m00_regslice_5 || ORIG_REF_NAME==system_m00_regslice_5} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/system/ip/system_m00_regslice_5/system_m00_regslice_5_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_2/system_auto_pc_2_ooc.xdc

# XDC: bd/system/system_ooc.xdc
