# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z015clg485-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.cache/wt [current_project]
set_property parent.project_path /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/ipcore [current_project]
update_ip_catalog
set_property ip_output_repo /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/hdl/system_wrapper.vhd
add_files /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_axi_clkwiz_0/system_axi_clkwiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_axi_clkwiz_0/system_axi_clkwiz_0.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_axi_clkwiz_0/system_axi_clkwiz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_axi_dma_mm2s_0/system_axi_dma_mm2s_0.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_axi_dma_mm2s_0/system_axi_dma_mm2s_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_axi_dma_s2mm_0/system_axi_dma_s2mm_0.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_axi_dma_s2mm_0/system_axi_dma_s2mm_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_axi_gp_rstgen_0/system_axi_gp_rstgen_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_axi_gp_rstgen_0/system_axi_gp_rstgen_0.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_axi_hp_rstgen_0/system_axi_hp_rstgen_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_axi_hp_rstgen_0/system_axi_hp_rstgen_0.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_core_clkwiz_0/system_core_clkwiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_core_clkwiz_0/system_core_clkwiz_0.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_core_clkwiz_0/system_core_clkwiz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_sys_core_rstgen_0/system_sys_core_rstgen_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_sys_core_rstgen_0/system_sys_core_rstgen_0.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_sys_cpu_0/system_sys_cpu_0.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_s00_regslice_6/system_s00_regslice_6_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_s00_regslice_6/system_s00_regslice_6_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_auto_cc_0/system_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_auto_cc_0/system_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_auto_cc_0/system_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_m01_regslice_0/system_m01_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_m01_regslice_0/system_m01_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_m02_regslice_0/system_m02_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_m02_regslice_0/system_m02_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_s00_regslice_7/system_s00_regslice_7_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_s00_regslice_7/system_s00_regslice_7_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_auto_us_0/system_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_auto_us_0/system_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_auto_us_0/system_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_auto_rs_w_0/system_auto_rs_w_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_auto_rs_w_0/system_auto_rs_w_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_s01_regslice_4/system_s01_regslice_4_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_s01_regslice_4/system_s01_regslice_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_m00_regslice_4/system_m00_regslice_4_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_m00_regslice_4/system_m00_regslice_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_s00_regslice_8/system_s00_regslice_8_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_s00_regslice_8/system_s00_regslice_8_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_auto_us_1/system_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_auto_us_1/system_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_auto_us_1/system_auto_us_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_auto_rs_w_1/system_auto_rs_w_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_auto_rs_w_1/system_auto_rs_w_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_s01_regslice_5/system_s01_regslice_5_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_s01_regslice_5/system_s01_regslice_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_m00_regslice_5/system_m00_regslice_5_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_m00_regslice_5/system_m00_regslice_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/ip/system_auto_pc_2/system_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/pablo/git/blog/matlab_libiio_axis/matlab/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/system/system_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top system_wrapper -part xc7z015clg485-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef system_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file system_wrapper_utilization_synth.rpt -pb system_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
