open_system('two_stage_hdl_coder');
open_system('gm_two_stage_hdl_coder');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_two_stage_hdl_coder/two stage downsampler/Discrete FIR Filter3', 'user2');
annotate_port('gm_two_stage_hdl_coder/two stage downsampler/Discrete FIR Filter3', 1, 1, 'Block not characterized');
hilite_system('two_stage_hdl_coder/two stage downsampler/Discrete FIR Filter3', 'user2');
annotate_port('two_stage_hdl_coder/two stage downsampler/Discrete FIR Filter3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_two_stage_hdl_coder/two stage downsampler/Discrete FIR Filter3', 'user2');
annotate_port('gm_two_stage_hdl_coder/two stage downsampler/Discrete FIR Filter3', 1, 1, 'Block not characterized');
hilite_system('two_stage_hdl_coder/two stage downsampler/Discrete FIR Filter3', 'user2');
annotate_port('two_stage_hdl_coder/two stage downsampler/Discrete FIR Filter3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_two_stage_hdl_coder/two stage downsampler/Discrete FIR Filter4', 'user2');
annotate_port('gm_two_stage_hdl_coder/two stage downsampler/Discrete FIR Filter4', 1, 1, 'Block not characterized');
hilite_system('two_stage_hdl_coder/two stage downsampler/Discrete FIR Filter4', 'user2');
annotate_port('two_stage_hdl_coder/two stage downsampler/Discrete FIR Filter4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_two_stage_hdl_coder/two stage downsampler/Discrete FIR Filter4', 'user2');
annotate_port('gm_two_stage_hdl_coder/two stage downsampler/Discrete FIR Filter4', 1, 1, 'Block not characterized');
hilite_system('two_stage_hdl_coder/two stage downsampler/Discrete FIR Filter4', 'user2');
annotate_port('two_stage_hdl_coder/two stage downsampler/Discrete FIR Filter4', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_two_stage_hdl_coder/two stage downsampler/Discrete FIR Filter3/Discrete FIR Filter3', 'user2');
annotate_port('gm_two_stage_hdl_coder/two stage downsampler/Discrete FIR Filter3/Discrete FIR Filter3', 1, 1, 'Block not characterized');
hilite_system('two_stage_hdl_coder/two stage downsampler/Discrete FIR Filter3', 'user2');
annotate_port('two_stage_hdl_coder/two stage downsampler/Discrete FIR Filter3', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_two_stage_hdl_coder/two stage downsampler/Discrete FIR Filter4/Discrete FIR Filter4', 'user2');
annotate_port('gm_two_stage_hdl_coder/two stage downsampler/Discrete FIR Filter4/Discrete FIR Filter4', 1, 1, 'Block not characterized');
hilite_system('two_stage_hdl_coder/two stage downsampler/Discrete FIR Filter4', 'user2');
annotate_port('two_stage_hdl_coder/two stage downsampler/Discrete FIR Filter4', 1, 1, 'Block not characterized');
